# Generated by Django 5.1.3 on 2024-12-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.CharField(default='', max_length=200),
        ),
    ]
